apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: server-java-web-app-1-7-azure
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: server-java-web-app-1-7-azure
    app.kubernetes.io/name: server-java-web-app-1-7-azure
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: scan_severity_gate
    value: none
  - name: ports
    value:
      - containerPort: 9000
        name: mon
        port: 9000
      - containerPort: 8080
        name: app
        port: 8080
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  source:
    git:
      url: ssh://git@github.com/Mpluya/tanzu-java-web-app-1-7-server
      ref:
        branch: main
